name: Release VSIX

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund
        working-directory: ./extensions/maiide-openrouter

      - name: Compile
        run: npm run compile
        working-directory: ./extensions/maiide-openrouter

      - name: Package VSIX
        run: npx @vscode/vsce package --out maiide-openrouter.vsix
        working-directory: ./extensions/maiide-openrouter

      - name: Create Release and Upload VSIX
        uses: softprops/action-gh-release@v1
        with:
          files: ./extensions/maiide-openrouter/maiide-openrouter.vsix
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
